<a href="https://colab.research.google.com/github/muthu287/Data-analytics-using-python-project/blob/main/Day_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

marks = np.array([90, 85, 78, 90])

print(marks[3])

90


In [ ]:
import numpy as np

marks = np.array([90, 85, 78,92, 80])

print(marks[1:4])

[85 78 92]


In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

new_arr = arr.reshape(2,3)

print(new_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

marks = np.array([70,80,90,60])

average = np.mean(marks)

print(average)

75.0


In [ ]:
salary = np.array([10000,20000,30000,40000,50000])

med = np.median(salary)

print(med)


30000.0
