<a href="https://colab.research.google.com/github/muthu287/Data-analytics-using-python-project/blob/main/Day_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
try:
  num=int(input("enter:"))
  print(num)
except:
  print("Invalid input")

enter:ab
Invalid input


In [ ]:
import numpy as np
marks=np.array([90,78,99,76,])
print(marks)

[90 78 99 76]


In [ ]:
import numpy as np
students=np.array([
   [90,78],
   [99,76],
   [88,54],
])
print(students)

[[90 78]
 [99 76]
 [88 54]]


In [ ]:
import numpy as np
arr=np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np
marks=np.array([90,78,99,76])
print(marks[2])

99


In [ ]:
import numpy as np
marks=np.array([98,88,87,94,66,79,])
print(marks[1:4])

[88 87 94]
